# Generated by Django 3.2 on 2021-04-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workout', models.CharField(choices=[('W', 'Weight'), ('C', 'Cardio'), ('B', 'Batting'), ('P', 'Position Training')], default='W', max_length=1)),
                ('dodger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dodger')),
            ],
        ),
    ]
